name = "mehmet-gulumser-chat"
main = "worker.js"
compatibility_date = "2026-02-27"

[vars]
TOP_K = "6"
MAX_REQ_PER_MINUTE_PER_IP = "8"
MAX_REQ_PER_DAY = "500"
MAX_REQ_PER_MONTH = "8000"
MAX_TOKENS_PER_DAY = "350000"
MAX_TOKENS_PER_MONTH = "7000000"
